[package]
name = "cliap"
version = "0.1.0"
edition = "2021"
description = "CLI Arg Parser backed by Serde data model"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
combine = "4.6.6"
delegate = "0.9.0"
enum-as-inner = "0.5.1"
nonempty = "0.8.1"
strum = { version = "0.24.1", features = ["derive"] }
